### ISSUE TITLE
Problem when sitting next to functions

### ISSUE THREAD

**Issue by alshdavid** [bashmish/es6-string-css#2]
When annotating css on the root level which comes from a function, syntax highlighting breaks.

Without css annotation:
![image](https://user-images.githubusercontent.com/12656294/61600775-c0f5dc00-ac75-11e9-98d4-ee992a3f247c.png)

With css annotation the code following the template loses highlighting
![image](https://user-images.githubusercontent.com/12656294/61600764-b4718380-ac75-11e9-97de-63279efc1f46.png)

**Comment by depadiernos** [comment]
I am also seeing this issue. The code still works but we lose highlighting for anything else below the variable with the css comment.
