### ISSUE TITLE
Remove from marketplace?

### ISSUE THREAD

**Issue by barneycarroll** [bashmish/es6-string-css#7]
Since v2.9.0, the canonical `es6-string-html` extension includes a more up-to-date CSS language feature as part of core – AFAICT this makes this extension redundant and confusing (I installed both, tried hacking at this to modify behaviour… then eventually found `es6-string-html` was superseding it 😅). Considering the noise of so many similar extensions in the marketplace, and the more regular & comprehensive updates to the core extension, might it be worth retiring this extension from the marketplace – or perhaps marking it as redundant?

**Comment by bashmish** [comment]
Looks like the `es6-string-html` doesn't support the css tag yet, but only supports the comment, so my extension still has a use case. I'm checking it from time to time, so once there is no need in my extension, I'll remove it. Thanks for the feedback :)
